// abilities for techies 6.84

"DOTAAbilities"
{
    "techies_land_mines_custom_684"
    {
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/heroes/techies/684/land_mines/land_mines"

        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
        "AbilityUnitDamageType"         "DAMAGE_TYPE_PHYSICAL"
        "SpellImmunityType"             "SPELL_IMMUNITY_ENEMIES_YES"

        "FightRecapLevel"               "1"
        "MaxLevel"                      "4"

        "AbilityTextureName"            "techies_land_mines"

        "AbilityCastRange"              "100"
        "AbilityCooldown"               "19 16 13 10"
        "AbilityManaCost"               "125 150 175 205"

        "AbilityCastAnimation"          "ACT_DOTA_CAST_ABILITY_1"

        "AbilityValues"
        {
            "damage"                    "300 375 450 525"
            "small_radius"
            {
                "value"                         "200"
                "affected_by_aoe_increase"      "1"
            }
            "big_radius"
            {
                "value"                         "500"
                "affected_by_aoe_increase"      "1"
            }
            "activation_time"           "0.5"
            "max_mines"                 "20"
            "explode_delay"             "0.3"
            "fade_time"                 "2.0"
        }
    }

    "techies_stasis_trap_custom_684"
    {
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/heroes/techies/684/stasis_trap/stasis_trap"

        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_NORMAL_WHEN_STOLEN | DOTA_ABILITY_BEHAVIOR_AOE"
        "SpellImmunityType"             "SPELL_IMMUNITY_ENEMIES_NO"

        "FightRecapLevel"               "1"
        "MaxLevel"                      "4"

        "AbilityTextureName"            "techies_stasis_trap"

        "AbilityCastRange"              "150"
        "AbilityCastPoint"              "1.0"
        "AbilityCooldown"               "20 16 13 10"
        "AbilityManaCost"               "80 110 140 160"

        "AbilityCastAnimation"          "ACT_DOTA_CAST_ABILITY_2"

        "AbilityValues"
        {
            "activation_radius"         "450"
            "explode_delay"             "1.5"
            "stun_radius"
            {
                "value"                         "450"
                "affected_by_aoe_increase"      "1"
            }
            "stun_duration"             "2.5 3 3.5 4"
            "activation_time"           "1.5"
            "fade_time"                 "2.0"
            "duration"                  "360.0"
        }
    }

    "techies_suicide_custom_684"
    {
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/heroes/techies/684/suicide/suicide"

        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_POINT"
        "AbilityUnitTargetTeam"         "DOTA_UNIT_TARGET_TEAM_ENEMY"
        "AbilityUnitTargetType"         "DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
        "SpellImmunityType"             "SPELL_IMMUNITY_ENEMIES_YES"
        "AbilityUnitDamageType"         "DAMAGE_TYPE_PHYSICAL"

        "FightRecapLevel"               "1"
        "MaxLevel"                      "4"

        "AbilityTextureName"            "techies_suicide_squad_attack"

        "AbilityCastRange"              "100"
        "AbilityCooldown"               "160 140 120 100"
        "AbilityManaCost"               "100 125 150 175"

        "AbilityCastAnimation"          "ACT_DOTA_CAST_ABILITY_3"

        "AbilityValues"
        {
            "small_radius"
            {
                "value"                         "200"
                "affected_by_aoe_increase"      "1"
            }
            "big_radius"
            {
                "value"                         "500"
                "affected_by_aoe_increase"      "1"
            }
            "vision_radius"
            {
                "value"                         "400"
                "affected_by_aoe_increase"      "1"
            }
            "damage"                    "500 650 850 1150"
            "partial_damage"            "260 300 340 380"
            "respawn_time_ptc"          "0.5"
            "respawn_time_tooltip"      "50"
        }
    }

    "techies_focused_detonate_custom_684"
    {
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/heroes/techies/684/focused_detonate/focused_detonate"

        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_UNRESTRICTED | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
        "AbilityUnitDamageType"         "DAMAGE_TYPE_MAGICAL"

        "DependentOnAbility"            "techies_remote_mines_custom_684"

        "MaxLevel"                      "1"

        "AbilityTextureName"            "techies_focused_detonate"

        "AbilityCooldown"               "1"

        "AbilityCastAnimation"          "ACT_DOTA_CAST_ABILITY_4"

        "AbilityValues"
        {
            "radius"
            {
                "value"                         "700"
                "affected_by_aoe_increase"      "1"
            }
        }
    }

    "techies_minefield_sign_custom_684"
    {
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/heroes/techies/684/minefield_sign/minefield_sign"

        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
        "AbilityUnitDamageType"         "DAMAGE_TYPE_NONE"

        "HasScepterUpgrade"             "1"

        "MaxLevel"                      "1"

        "AbilityTextureName"            "techies_minefield_sign"

        "AbilityCastRange"              "10"
        "AbilityCooldown"               "360"

        "AbilityCastAnimation"          "ACT_DOTA_IDLE"

        "AbilityValues"
        {
            "aura_radius"
            {
                "value"                         "125"
                "affected_by_aoe_increase"      "1"
                "RequiresScepter"               "1"
            }
            "lifetime"                  "180"
        }
    }

    "techies_remote_mines_custom_684"
    {
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/heroes/techies/684/remote_mines/remote_mines"

        "AbilityType"                   "ABILITY_TYPE_ULTIMATE"
        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_NORMAL_WHEN_STOLEN"
        "AbilityUnitDamageType"         "DAMAGE_TYPE_MAGICAL"
        "SpellImmunityType"             "SPELL_IMMUNITY_ENEMIES_NO"

        "HasScepterUpgrade"             "1"

        "FightRecapLevel"               "2"
        "MaxLevel"                      "3"

        "AbilityTextureName"            "techies_remote_mines"

        "AbilityCastPoint"              "1.5"
        "AbilityCooldown"               "10.0"
        "AbilityManaCost"               "200 240 300"

        "AbilityCastAnimation"          "ACT_DOTA_CAST_ABILITY_6"

        "AbilityValues"
        {
            "damage"
            {
                "value"                     "300 450 600"
                "special_bonus_scepter"     "+150"
                "DamageTypeTooltip"         "DAMAGE_TYPE_MAGICAL"
            }
            "radius"
            {
                "value"                         "425"
                "affected_by_aoe_increase"      "1"
            }
            "duration"                  "600"
            "activation_time"           "2.0"
            "vision_radius"
            {
                "value"                         "500"
                "affected_by_aoe_increase"      "1"
            }
            "vision_duration"           "3.0"
            "model_scale"               "0.0 10.0 20.0"
            
            "scepter_bonus_castrange"
            {
                "value"                         "0"
                "special_bonus_scepter"         "=200"
                "RequiresScepter"               "1"
            }
            "AbilityCastRange"
            {
                "value"                     "500"
                "special_bonus_scepter"     "+200"
            }
        }
    }

    "techies_remote_mines_self_detonate_custom_684"
    {
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/heroes/techies/684/remote_mines/self_detonate"

        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
        "AbilityUnitDamageType"         "DAMAGE_TYPE_MAGICAL"

        "MaxLevel"                      "1"

        "AbilityTextureName"            "techies_remote_mines_self_detonate"

        "AbilityCooldown"               "1"

        "AbilityValues"
        {
            "radius"
            {
                "value"                         "425"
                "affected_by_aoe_increase"      "1"
            }
        }
    }
}