// abilities for techies 7.25

"DOTAAbilities"
{
    "techies_land_mines_custom_725"
    {
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/heroes/techies/725/land_mines/land_mines"

        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
        "AbilityUnitDamageType"         "DAMAGE_TYPE_MAGICAL"
        "SpellDispellableType"          "SPELL_DISPELLABLE_YES"
        "SpellImmunityType"             "SPELL_IMMUNITY_ENEMIES_NO"

        "HasScepterUpgrade"             "1"

        "FightRecapLevel"               "1"
        "MaxLevel"                      "4"

        "AbilityTextureName"            "techies_land_mines"

        "AbilityCastRange"              "100"
        "AbilityCharges"                "3"
        "AbilityChargeRestoreTime"      "23"
        "AbilityManaCost"               "110 130 150 170"

        "AbilityCastAnimation"          "ACT_DOTA_CAST_ABILITY_1"

        "AbilityValues"
        {
            "radius"
            {
                "value"                         "400"
                "affected_by_aoe_increase"      "1"
            }
            "proximity_threshold"               "1.6"
            "damage"
            {
                "value"                         "200 400 600 800"
                "CalculateSpellDamageTooltip"   "0"
            }
            "building_damage_pct"
            {
                "value"                         "25.0"
                "CalculateSpellDamageTooltip"   "0"
            }
            "activation_delay"                  "1.75"
            "placement_radius"                  "400"
            "mines_move"
            {
                "value"                                         "0"
                "special_bonus_unique_techies_725_custom_4"     "+75"
            }
            "scepter_bonus_castrange"
            {
                "value"                         "0"
                "special_bonus_scepter"         "=300"
                "RequiresScepter"               "1"
            }
            "AbilityCastRange"
            {
                "value"                         "100"
                "special_bonus_scepter"         "+300"
            }
            "AbilityChargeRestoreTime"
            {
                "value"                                         "23.0"
                "special_bonus_unique_techies_725_custom"       "-4"
            }
        }
    }

    "techies_stasis_trap_custom_725"
    {
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/heroes/techies/725/stasis_trap/stasis_trap"

        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_NORMAL_WHEN_STOLEN | DOTA_ABILITY_BEHAVIOR_AOE"
        "SpellImmunityType"             "SPELL_IMMUNITY_ENEMIES_NO"
        "SpellDispellableType"          "SPELL_DISPELLABLE_YES"

        "HasScepterUpgrade"             "1"

        "FightRecapLevel"               "1"
        "MaxLevel"                      "4"

        "AbilityTextureName"            "techies_stasis_trap"

        "AbilityCastRange"              "150"
        "AbilityCastPoint"              "1.0"
        "AbilityCooldown"               "20.0 16.0 13.0 10.0"
        "AbilityManaCost"               "80 110 140 160"

        "AbilityCastAnimation"          "ACT_DOTA_CAST_ABILITY_2"

        "AbilityValues"
        {
            "activation_radius"
            {
                "value"                     "400"
                "affected_by_aoe_increase"  "1"
            }
            "root_radius"
            {
                "value"                     "600"
                "affected_by_aoe_increase"  "1"
            }
            "root_duration"                 "2.0 3.0 4.0 5.0"
            "activation_time"               "2.0"
            "fade_time"                     "2.0"
            "mines_move"
            {
                "value"                                         "0"
                "special_bonus_unique_techies_725_custom_4"     "+75"
            }
            "scepter_bonus_castrange"
            {
                "value"                         "0"
                "special_bonus_scepter"         "=300"
                "RequiresScepter"               "1"
            }
            "AbilityCastRange"
            {
                "value"                     "150"
                "special_bonus_scepter"     "+300"
            }
        }
    }

    "techies_suicide_custom_725"
    {
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/heroes/techies/725/suicide/suicide"

        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_NORMAL_WHEN_STOLEN"
        "AbilityUnitTargetTeam"         "DOTA_UNIT_TARGET_TEAM_ENEMY"
        "SpellImmunityType"             "SPELL_IMMUNITY_ENEMIES_NO"
        "AbilityUnitDamageType"         "DAMAGE_TYPE_MAGICAL"
        "SpellDispellableType"          "SPELL_DISPELLABLE_YES"

        "FightRecapLevel"               "1"
        "MaxLevel"                      "4"

        "AbilityTextureName"            "techies_suicide"

        "AbilityCastRange"              "1000"
        "AbilityCastPoint"              "1.0"
        "AbilityManaCost"               "100 125 150 175"

        "AbilityCastAnimation"          "ACT_DOTA_CAST_ABILITY_3"

        "AbilityValues"
        {
            "radius"
            {
                "value"                     "400"
                "affected_by_aoe_increase"  "1"
            }
            "damage"
            {
                "value"                                         "300 400 500 600"
                "special_bonus_unique_techies_725_custom_2"     "+300"
            }
            "silence_duration"          "4.0 5.0 6.0 7.0"
            "hp_cost"                   "50.0"
            "duration"                  "0.75"
            "AbilityCooldown"
            {
                "value"                                         "35"
                "special_bonus_unique_techies_725_custom_3"     "-28"
            }
        }
    }

    "techies_minefield_sign_custom_725"
    {
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/heroes/techies/725/minefield_sign/minefield_sign"

        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_SHOW_IN_GUIDES | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
        "AbilityUnitDamageType"         "DAMAGE_TYPE_NONE"

        "HasScepterUpgrade"             "1"

        "MaxLevel"                      "1"

        "AbilityTextureName"            "techies_minefield_sign"

        "AbilityCastRange"              "10"
        "AbilityCooldown"               "360"

        "AbilityCastAnimation"          "ACT_DOTA_IDLE"
        
        "AbilityValues"
        {
            "aura_radius"
            {
                "value"                         "175"
                "affected_by_aoe_increase"      "1"
                "RequiresScepter"               "1"
            }
            "lifetime"                          "180"
        }
    }

    "techies_focused_detonate_custom_725"
    {
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/heroes/techies/725/focused_detonate/focused_detonate"

        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_UNRESTRICTED | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_SHOW_IN_GUIDES"
        "AbilityUnitDamageType"         "DAMAGE_TYPE_MAGICAL"

        "DependentOnAbility"            "techies_remote_mines_custom_725"

        "MaxLevel"                      "1"

        "AbilityTextureName"            "techies_focused_detonate"

        "AbilityCooldown"               "1.0"

        "AbilityValues"
        {
            "radius"
            {
                "value"                     "700"
                "affected_by_aoe_increase"  "1"
            }
        }
    }

    "techies_remote_mines_custom_725"
    {
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/heroes/techies/725/remote_mines/remote_mines"

        "AbilityType"                   "ABILITY_TYPE_ULTIMATE"
        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_NORMAL_WHEN_STOLEN"
        "AbilityUnitDamageType"         "DAMAGE_TYPE_MAGICAL"
        "SpellImmunityType"             "SPELL_IMMUNITY_ENEMIES_NO"

        "LinkedAbility"                 "techies_focused_detonate_custom"

        "HasScepterUpgrade"             "1"

        "FightRecapLevel"               "2"
        "MaxLevel"                      "3"

        "AbilityTextureName"            "techies_remote_mines"

        "AbilityCastRange"              "500"
        "AbilityCastPoint"              "1.0"
        "AbilityCooldown"               "8"
        "AbilityManaCost"               "120 180 240"

        "AbilityCastAnimation"          "ACT_DOTA_CAST_ABILITY_6"

        "AbilityValues"
        {
            "damage"
            {
                "value"                         "300 450 600"
                "special_bonus_scepter"         "+150"
                "CalculateSpellDamageTooltip"   "0"
                "DamageTypeTooltip"             "DAMAGE_TYPE_MAGICAL"
            }
            "radius"
            {
                "value"                     "425"
                "affected_by_aoe_increase"  "1"
            }
            "duration"                  "600.0"
            "activation_time"           "2.0"
            "vision_radius"
            {
                "value"                     "500"
                "affected_by_aoe_increase"  "1"
            }
            "vision_duration"           "3.0"
            "model_scale"               "0.0 10.0 20.0"
            "detonate_delay"            "0.25"
            "mines_move"
            {
                "value"                                         "0"
                "special_bonus_unique_techies_725_custom_4"     "+75"
            }
            "scepter_bonus_castrange"
            {
                "value"                         "0"
                "special_bonus_scepter"         "=300"
                "RequiresScepter"               "1"
            }
            "AbilityCastRange"
            {
                "value"                     "500"
                "special_bonus_scepter"     "+300"
            }
        }
    }

    "techies_remote_mines_self_detonate_custom_725"
    {
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/heroes/techies/725/remote_mines/self_detonate"

        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
        "AbilityUnitDamageType"         "DAMAGE_TYPE_MAGICAL"

        "MaxLevel"                      "1"

        "AbilityTextureName"            "techies_remote_mines_self_detonate"

        "AbilityValues"
        {
            "radius"
            {
                "value"                     "425"
                "affected_by_aoe_increase"  "1"
            }
        }
    }

    //=========================//
    //         TALENTS         //
    //=========================//

    // -4s Proximity Mines cooldown
    "special_bonus_unique_techies_725_custom"
    {
        "BaseClass"                     "special_bonus_base"
        "AbilityType"                   "ABILITY_TYPE_ATTRIBUTES"
        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_PASSIVE"
    }

    // +300 Blast Off! damage
    "special_bonus_unique_techies_725_custom_2"
    {
        "BaseClass"                     "special_bonus_base"
        "AbilityType"                   "ABILITY_TYPE_ATTRIBUTES"
        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_PASSIVE"
    }

    // -28 Blast Off! cooldown
    "special_bonus_unique_techies_725_custom_3"
    {
        "BaseClass"                     "special_bonus_base"
        "AbilityType"                   "ABILITY_TYPE_ATTRIBUTES"
        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_PASSIVE"
    }

    // +75 Mines movement speed
    "special_bonus_unique_techies_725_custom_4"
    {
        "BaseClass"                     "special_bonus_base"
        "AbilityType"                   "ABILITY_TYPE_ATTRIBUTES"
        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_PASSIVE"
    }
}